### ISSUE TITLE
Update docker image for more user-friendly usage

### ISSUE THREAD

**Issue by jiacai2050** [apache/incubator-horaedb#1285]
### Describe This Problem

If new users try ceresdb with docker image, there is no easy way for them to explore data stored in ceresdb. 

### Proposal

Since ceresdb already support many query protocol, we can include following tools in docker images to help users explore :
- mysql client
- grafana, with ceresdb added as data source by default.

In this way, users can either explore in terminal or web UI.

**Comment by dracoooooo** [comment]
Hi, I would like to do this task, please assign this issue to me.

**Comment by jiacai2050** [comment]
Thanks, assigned.

**Comment by dracoooooo** [comment]
> Can HoraeDB be used directly as a datasource for Grafana, or is it necessary to install Prometheus first?

Oh I found the doc in [Ecosystem/InfluxDB](https://horaedb.apache.org/en/ecosystem/influxdb.html). [Operation/Observability](https://horaedb.apache.org/en/operation/observability.html#observability) seems to be outdated with typo and broken picture. I will also update this doc later.
