### ISSUE TITLE
Refactor write/read error message

### ISSUE THREAD

**Issue by ZuLiangWang** [apache/incubator-horaedb#1293]
### Describe This Problem

CeresDB currently handles user error messages unreasonably. When a shard is in the `frozen` state, the error message when reading or writing the tables in this shard is `Table not found`, which misleads users.s

### Proposal

Refactor error message, when a shard is in the `frozen` state, reading or writing the tables in this shard throw error like `shard state is invalid`

**Comment by jiacai2050** [comment]
I plan to fix this misleading error message this week.

**Comment by jiacai2050** [comment]
https://github.com/apache/incubator-horaedb/pull/1418  add shard status when table is not found, this should be enough for debugging.
