### ISSUE TITLE
Rename all occurance of CeresDB into HoraeDB

### ISSUE THREAD

**Issue by tisonkun** [apache/incubator-horaedb#1319]
Let's search and replace it globally where it should be HoraeDB now.

* [ ] #1329
* [x] Update all CeresDB URLs after repo transferred

**Comment by tisonkun** [comment]
We won't change the GitHub org name "CeresDB" now. It will be done once we transfer the repo.

**Comment by tisonkun** [comment]
Ditto for the docs site [ceresdb.github.io/docs](https://ceresdb.github.io/docs). We will change it once we transfer the repo.

**Comment by tisonkun** [comment]
* [ ] The first step should be rename ceresdbproto to horaedbproto as it's a root dependency.
* [ ]

**Comment by tematou** [comment]
![image](https://github.com/CeresDB/horaedb/assets/35472988/00e17283-380f-41de-8245-9d2013edf18f)
被京东收购了？

**Comment by tisonkun** [comment]
@tematou This is a coincident name conflict while the post you refer to should be years ago.

You can take a look at [this proposal](https://cwiki.apache.org/confluence/display/INCUBATOR/HoraeDB+Proposal) that HoraeDB (this project) is going to enter the ASF incubator.

I'll hide your comment as Off Topic and Resolved.

**Comment by tisonkun** [comment]
Most of the tasks are done. Closing...
