### ISSUE TITLE
Rolling update from "CeresDB" binaries and libraries to the new "HoraeDB" ones

### ISSUE THREAD

**Issue by tisonkun** [apache/incubator-horaedb#1329]
We should discuss about how the existing CeresDB provisions and libraries can be rolling updated to the new "HoraeDB" ones.

For example, we may duplicate the service `CeresmetaRpcService` with `HoraeMetaRpcService`. Release a version that contains both of these two endpoint, and a new one that only the `HoraeMetaRpcService` exists.

**Comment by tematou** [comment]
![image](https://github.com/CeresDB/horaedb/assets/35472988/baa37980-090f-482c-9acb-134aac07286f)
被京东收购了？

**Comment by tisonkun** [comment]
@chunshao90 @jiacai2050 @tanruixiang do we have a resolution now? Maybe we can close this issue with the resolution. Or we'll have a plan to finish it.

**Comment by chunshao90** [comment]
> @chunshao90 @jiacai2050 @tanruixiang do we have a resolution now? Maybe we can close this issue with the resolution. Or we'll have a plan to finish it.

I've been dealing with it recently and expect it to be resolved within a week.

**Comment by jiacai2050** [comment]
This https://github.com/apache/incubator-horaedb/pull/1455 list what are required to upgrade to latest main branch.

During the update process, there will be errors between horaedb-server and horaemeta, but should be fine when all servers updated.
