### ISSUE TITLE
feat：align README documents in both English and Chinese

### ISSUE THREAD

**Issue by caicancai** [apache/incubator-horaedb#1342]
### Describe This Problem

The README document and the REAME-CN content are not aligned.

### Proposal

I think we should align the README English and Chinese documents

**Comment by caicancai** [comment]
> Thank you for your suggestions. The English version is expected to undergo a major revision in the coming weeks, so we can wait until the English version is revised and aligned.

Thank you for your reply. If you need help, I can provide it

**Comment by tisonkun** [comment]
> because horaedb-server doesn't exist in docker hub yet

Let's hold a bit after repo transfer happened and new release happened.

You can go back here then.

**Comment by caicancai** [comment]
> > because horaedb-server doesn't exist in docker hub yet
> 
> Let's hold a bit after repo transfer happened and new release happened.
> 
> You can go back here then.

thank you.

**Comment by caicancai** [comment]
@tanruixiang Maybe I can start this part of the work now? I have noticed that there are no major updates to README-CN at the moment

**Comment by caicancai** [comment]
@tanruixiang I noticed that there was a pr who did this part of my work
