### ISSUE TITLE
[DISCUSS][VOTE]: Some breaking changes resulting from the renaming of `CeresDB` to `HoraeDB`

### ISSUE THREAD

**Issue by chunshao90** [apache/incubator-horaedb#1373]
### Describe This Problem

Due to the renaming of `CeresDB` to `Horaedb`, some breaking changes have occurred.
Refer to #1319

#### Plan 1: Compatibility Upgrade
Support for separate upgrades of Horaedb and Horaemeta, with version compatibility.
For instance, if there are incompatible service interfaces in `horaedbproto`, one could define two service names, `HoraeMeta` and `HoraeDB`, and implement two sets of services for compatibility.

Disadvantages: Compatibility upgrades are quite costly and would result in a lot of temporary code.

#### Plan 2: Incompatible Upgrade
`HoraeDB` releases a new major version that is not compatible with historical versions, users need to upgrade `HoraeDB` and `HoraeMeta` at same time. As a result, the service will be unavailable for longer time than plan 1.

### Additional Context

If you're using CeresDB in production or interested in this project, please share your ideas about which plan you prefer.

You can use :+1: in comments below to express your choice. 

> Note: The vote will be lasting for one week(2023-12-25).

**Comment by jiacai2050** [comment]
1

**Comment by jiacai2050** [comment]
2

**Comment by tanruixiang** [comment]
Once the mailbox and transfer are set up, it is recommended to use either the `dev@horaedb.apache.org` or `github.com/apache/incubator-horaedb/discussions` for discussion or voting.

**Comment by tisonkun** [comment]
Shall we conclude now?

**Comment by chunshao90** [comment]
Conclude: we will adopt `Plan 2: Incompatible Upgrade`.
