### ISSUE TITLE
Improve the readability of error messages

### ISSUE THREAD

**Issue by ZuLiangWang** [apache/incubator-horaedb#1386]
### Describe This Problem

Currently, the error information in HoraeDB is unclear (for example, In many cases, users will see the error `table not found`.). When an error occurs, it confuses users and increases the difficulty of troubleshooting and locating problems.

### Proposal

Make error messages clearer, classify error messages, and even consider designing error codes to classify error messages in the form of error codes.

**Comment by tanruixiang** [comment]
May be we can make a example and split tasks into modules and track them. cc @ShiKaiWi

**Comment by jiacai2050** [comment]
Fixed in #1418
